.echo on
.mode column
.headers on
.nullvalue NULL

insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("110X","An Unrestricted Line Officer who is not qualified in any warfare specialty or in training for any warfare specialty","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("111X","An Unrestricted Line Officer who is qualified in Surface Warfare","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("112X","An Unrestricted Line Officer who is qualified in Submarine Warfare","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("113X","An Unrestricted Line Officer who is qualified in Special Warfare","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("114X","An Unrestricted Line Officer who is qualified in Explosive Ordnance Disposal (EOD) Warfare","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("116X","Unrestricted Line Officer who is in training for Surface Warfare qualification","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("117X","Unrestricted Line Officer who is in training for Submarine Warfare qualification","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("118X","Unrestricted Line Officer who is in training for Special Warfare qualification","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("119X","Unrestricted Line Officer who is in training for Explosive Ordnance Disposal qualification","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("120X","Special Duty Officer - Human Resource Officer A Restricted Line Officer of the Human Resources Community who will plan, program and execute life-cycle management of our Navy's most important resource - people.","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("121X","Restricted Line Officer (Nuclear Power School Instructor) regulated by Program Authorization 100B.","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("1230","Restricted Line Officer (Permanent Military Professor) regulated by OPNAVINST 1520.40","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("128X","Special Duty Officer-Permanent Professional Recruiter Officer (Reserve Recruiting) (LT and LCDR)","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("130X","An Unrestricted Line Officer who is a member of the aeronautical community and whose rating as a pilot or NFO has been terminated. (These officers may be assigned to 1000, 1050, 1300, 1310 or 1320 designated billets, if otherwise qualified.)","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("131X","An Unrestricted Line Officer who is qualified for duty involving flying heavier-than-air, or heavier and lighter-than-air type of aircraft as a pilot","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("132X","An Unrestricted Line Officer who is qualified for duty involving flying heavier-than-air or heavier and lighter-than-air type aircraft as a Naval Flight Officer","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("137X","An Unrestricted Line Officer who is in training for duty involving flying as a Naval Flight Officer","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("139X","An Unrestricted Line Officer who is in training for duty involving flying as a pilot","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("144X","Engineering Duty Officer who is qualified as a Ship Engineering specialist IAW MILPERSMAN 1210-190. They include specialists in Ship and Ship systems Engineering, Electronic Systems Engineering, Combat/Weapons Systems Engineering, and Ordnance Systems Engineering","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("146X","Engineering Duty Officer who is in the process of completing the prescribed program leading to designation as 144X","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("150X","A Restricted Line AED Flag Officer or Captain who was formerly either an AED officer (Aerospace Engineering--designator 151X) or an AMD officer (Aviation Maintenance--designator 152X)","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("151X","Aerospace Engineering Duty Officer (Aerospace Engineering)","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("154X","Aviation Duty Officer","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("165X","Special Duty Officer - Public Affairs","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("166X","Special Duty Officer – Strategic Sealift Officer (SSO)","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("168X","Special Duty Officer (Reserve Recruiting)","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("171X","Special Duty Officer qualified as a Foreign Area Officer","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("180X","Special Duty Officer - Oceanography","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("181X","Special Duty Officer – Cryptologic Warfare Officer","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("182X","Special Duty Officer – Information Professional Officer","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("183X","Special Duty Officer – Intelligence Officer","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("184X","Special Duty Officer – Cyber Warfare Engineer","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("186X","Special Duty Officer – IWC Flag Officer","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("187X","Special Duty Officer - Maritime Space Officer","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("188X","Special Duty Officer - Maritime Cyber Warfare Officer (O1 to O6)","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("190X","An Unrestricted Line Officer under instruction as a prospective Nurse Corps officer","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("191X","An Unrestricted Line Officer under instruction as a prospective Medical Corps officer (Senior Medical Student)","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("192X","An Unrestricted Line Officer under instruction as a prospective Dental Corps officer","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("193X","An Unrestricted Line Officer under instruction as a prospective Medical Service officer (Optometry)","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("194X","An Unrestricted Line Officer under instruction as a prospective Chaplain Corps officer","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("195X","An Unrestricted Line Officer under instruction as a prospective Judge Advocate General's Corps officer","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("196X","An Unrestricted Line Officer under instruction as a prospective Medical Corps officer (Medical /Osteopathic Scholarship Program)","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("197X","An Unrestricted Line Officer under instruction in the Armed Forces Health Professions Scholarship Program (Medical/Osteopathic)","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("198X","An Unrestricted Line Officer under instruction in the Armed Forces Health Professions Scholarship Program (Dental)","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("199X","An Unrestricted Line Officer under instruction in the Armed Forces Health Professions Scholarship Program (Medical Service Corps)","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("210X","A Medical Corps Officer","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("220X","A Dental Corps Officer","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("230X","A Medical Service Corps Officer","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("250X","A Judge Advocate General Corps Officer","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("270X","Active duty Nurse Corps, Medical Service Corps, Medical Corps, and Dental Corps officer in rank of O7","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("290X","A Nurse Corps Officer","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("310X","A Supply Corps Officer","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("316X","A direct commissioned Supply Corps Officer in training for qualification","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("410X","A Chaplain Corps Officer","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("510X","A Civil Engineer Corps Officer","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("611X","A Limited Duty Officer (Deck - Surface)","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("612X","A Limited Duty Officer (Operations - Surface)","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("613X","A Limited Duty Officer (Engineering/Repair - Surface)","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("616X","A Limited Duty Officer (Ordnance - Surface)","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("618X","A Limited Duty Officer (Electronics - Surface)","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("620X","A Limited Duty Officer (Nuclear Power); Formerly DESIG 640X","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("621X","A Limited Duty Officer (Deck - Submarine)","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("623X","A Limited Duty Officer (Engineering/Repair - Submarine)","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("626X","A Limited Duty Officer (Ordnance - Submarine)","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("628X","A Limited Duty Officer (Electronics - Submarine)","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("629X","A Limited Duty Officer (Communications - Submarine)","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("631X","A Limited Duty Officer (Aviation Deck)","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("632X","A Limited Duty Officer (Aviation Operations)","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("633X","A Limited Duty Officer (Aviation Maintenance)","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("636X","A Limited Duty Officer (Aviation Ordnance)","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("639X","A Limited Duty Officer (Air Traffic Control)","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("641X","A Limited Duty Officer (Administration)","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("643X","A Limited Duty Officer (Bandmaster)","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("647X","A Limited Duty Officer (Photography)","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("648X","A Limited Duty Officer (Explosive Ordnance Disposal)","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("649X","A Limited Duty Officer (Security)","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("651X","A Limited Duty Officer of the Supply Corps","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("653X","A Limited Duty Officer of the Civil Engineer Corps","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("655X","A Limited Duty Officer of the Judge Advocate General Corps","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("680X","A Limited Duty Officer (Meteorology/Oceanography) Formerly DESIG 646X","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("681X","A Limited Duty Officer (Cryptologic Warfare) Formerly DESIG 644X","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("682X","A Limited Duty Officer (Information Professional) Formerly DESIG 642X","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("683X","A Limited Duty Officer (Intelligence) Formerly DESIG 645X","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("711X","Boatswain (Surface)","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("712X","Operations Technician (Surface)","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("713X","Engineering Technician (Surface)","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("715X","Special Warfare Technician","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("716X","Ordnance Technician (Surface)","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("717X","A Chief Warrant Officer with sophisticated, technical knowledge in all aspects of the Naval Special Warfare Combat Crewman","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("718X","Electronics Technician (Surface)","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("720X","Diving Officer","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("721X","Boatswain (Submarine)","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("723X","Engineering Technician (Submarine)","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("724X","Repair Technician (Submarine)","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("726X","Ordnance Technician (Submarine)","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("728X","Acoustic Technician","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("731X","Aviation Boatswain","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("732X","Aviation Operations Technician","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("733X","Aviation Maintenance Technician","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("736X","Aviation Ordnance Technician","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("737X","Air Vehicle Pilot","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("740X","Nuclear Power Technician","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("741X","Ship's Clerk","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("748X","Explosive Ordnance Disposal Technician","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("749X","Security Technician","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("751X","Supply Corps Warrant","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("752X","Food Service Warrant","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("753X","Civil Engineering Warrant","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("756X","Technical Nurse","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("780X","Oceanography Warrant Officer","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("781X","Cryptologic Warfare Technician Formerly DESIG 744X","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("782X","Information Systems Technician Formerly DESIG 742X","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("783X","Intelligence Technician Formerly DESIG 745X","NAVPERS 15839I VOL I (JAN 2024)");
insert into FTS_officer_designator_codes (suggest_text_1, suggest_text_2, source) values ("784X","Cyber Warrant Officer Formerly DESIG 743X","NAVPERS 15839I VOL I (JAN 2024)");

