apply plugin: 'com.android.application'
apply plugin: 'com.diffplug.spotless'


android {

    compileSdk = 37

    // https://developer.android.com/studio/build/shrink-code#keep-code
    // 20210130: Currently I do not build Android App Bundles, so the below is not used
    android.buildTypes.release.ndk.debugSymbolLevel = 'FULL'

    // TO-DO: Do this after each release
    // If your project builds an APK, use the build.gradle build setting shown earlier to generate
    // the native debug symbols file separately. Manually upload the native debug symbols file to
    // the Google Play Console. As part of the build process, the Android Gradle plugin outputs
    // this file in the following project location:
    //app/build/outputs/native-debug-symbols/variant-name/native-debug-symbols.zip

    defaultConfig {
        applicationId = "com.crashtestdummylimited.navydecoderplus"
        minSdk = 26
        targetSdk = 37
        versionCode = 50
        versionName = "1.46"
    }

    buildFeatures {
        viewBinding = true
        buildConfig = true
    }

    buildTypes {
        release {
            // Enables code shrinking, obfuscation, and optimization for only
            // your project's release build type.
            minifyEnabled = true

            // Enables resource shrinking, which is performed by the
            // Android Gradle plugin.
            shrinkResources = true

            // Includes the default ProGuard rules files that are packaged with
            // the Android Gradle plugin. To learn more, go to the section about
            // R8 configuration files.
            proguardFiles getDefaultProguardFile(
                    'proguard-android-optimize.txt'),
                    'proguard-rules.pro'
            // Pre 20210130 line
            //proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-project.txt'
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }
    namespace = 'com.crashtestdummylimited.navydecoderplus'
}

tasks.withType(JavaCompile).configureEach {
    options.compilerArgs << "-Xlint:unchecked"
    options.compilerArgs << "-Xlint:deprecation"
}

spotless {
    java {
        target 'src/main/java/**/*.java', 'src/test/java/**/*.java', 'src/androidTest/java/**/*.java'
        googleJavaFormat('1.35.0')
        removeUnusedImports()
        trimTrailingWhitespace()
        endWithNewline()
    }
    format 'xml', {
        target 'src/main/**/*.xml', 'src/test/**/*.xml'
        trimTrailingWhitespace()
        leadingTabsToSpaces(4)
        endWithNewline()
    }
}

dependencies {
    implementation 'com.google.android.play:review:2.0.2'
    implementation 'com.google.android.play:app-update:2.1.0'
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'com.google.android.material:material:1.14.0'
    implementation 'androidx.recyclerview:recyclerview:1.4.0'
}

// To fix issue per https://stackoverflow.com/questions/75274720/a-failure-occurred-while-executing-appcheckdebugduplicateclasses/75315276#75315276
configurations.implementation {
    exclude group: 'org.jetbrains.kotlin', module: 'kotlin-stdlib-jdk8'
}
